language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install zope.testrunner coverage coveralls
  - pip install -e .[test]
script:
  - coverage run -m zope.testrunner --test-path=src -vc
after_success:
  - coveralls
notifications:
  email: false
cache: pip
